# Generated by Django 2.2.1 on 2020-04-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='weight',
            field=models.FloatField(verbose_name='载重'),
        ),
    ]
